name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black ruff isort
    - name: Lint with ruff
      continue-on-error: true
      run: |
        ruff check . --select=E,F,W --ignore=E501
    - name: Check formatting with black
      continue-on-error: true
      run: |
        black --check .
    - name: Check imports with isort
      continue-on-error: true
      run: |
        isort --check-only --profile black .

  # Optional type-check job that won't fail the build
  type-check:
    runs-on: ubuntu-latest
    continue-on-error: true  # Make this job optional
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install mypy types-requests
    - name: Type check with mypy
      run: |
        mypy bmw_agents --ignore-missing-imports --no-strict-optional 